# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
dist: trusty
cache: packages
latex: false

r:
  - release
  - devel
os:
  - linux
  - osx

matrix:
  allow_failures:
    - r: devel

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"
